### ISSUE TITLE
Doesn't work with Lineage on Moto G8 Plus 

### ISSUE THREAD

**Issue by snoweuph** [StarGate01/NFCPresenceFix#1]
![Screenshot_20240620-165846_AusweisApp.png](https://github.com/StarGate01/NFCPresenceFix/assets/76737863/eda56aa7-62e5-4e02-b340-cc64e67d8c52)

**Comment by snoweuph** [comment]
Im using Lineage PHHP Treble GSI

**Comment by snoweuph** [comment]
Needed to 2, and not just 1 reboot

**Comment by StarGate01** [comment]
Please reboot your phone, try again, and then post the log from LSPosed->Logs->Module Logs

Edit: Oh nice to see you got it working :)
